command:
  - "/opt/keycloak/bin/kc.sh"
  - "--verbose"
  - "start-dev"

extraEnv: |
  - name: KEYCLOAK_ADMIN
    value: "admin"
  - name: KEYCLOAK_ADMIN_PASSWORD
    value: "secret"
  - name: KC_METRICS_ENABLED
    value: "true"
  - name: KC_HTTP_RELATIVE_PATH
    value: "/auth"
  - name: JAVA_OPTS_APPEND
    value: >-
      -XX:+UseContainerSupport
      -XX:MaxRAMPercentage=50.0
      -Djava.net.preferIPv4Stack=true
      -Djava.awt.headless=true

database:
  vendor: dev-file
  username: admin
  password: secret

test:
  enabled: true
